jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

language: clojure
lein: lein2
script: lein2 with-profile dev trampoline midje

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname